# Generated by Django 5.1.4 on 2025-02-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapelog',
            name='progress_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
